# Generated by Django 5.2.1 on 2025-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'empmodel',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'managed': True, 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelTable(
            name='studentmodel',
            table='studentmodel',
        ),
    ]
